---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: tdb-ubuntu1204-v9
    box_url: http://ci.mojolingo.com/job/Telephony-Dev-Box-Base-Boxen/9/artifact/tdb-ubuntu1204.box

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[sipp_test]
  attributes: {}
